spring:
  datasource:
    url: jdbc:mysql://192.168.207.12:49154/mysql?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 1200000
      connection-timeout: 20000
      connection-test-query: SELECT 1 from DUAL
  redis:
    host: 192.168.207.12
    port: 6379
    password:
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0